{% set name = "bytewax" %}
{% set version = "0.17.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bytewax/bytewax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: acf83b61cedf8e77547d226e2bd710ec613d5dae796a127404815e81cb1f7eb6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - maturin
  host:
    - python
    - pip
    - pkg-config
    - make
    - cmake
    - maturin
    - jsonpickle
    - libzlib
    - openssl
    - cyrus-sasl
    - perl  # [ win ]
    - protobuf
    - librdkafka
  run:
    - python
    - protobuf
    - jsonpickle
    - libzlib
    - librdkafka
    - python-confluent-kafka

test:
  source_files:
    - conftest.py
    - pytests
    - examples
  requires:
    - pytest
    - jsonpickle
  commands:
    - pytest -vvs ./pytests

about:
  home: https://bytewax.io
  dev_url: https://github.com/bytewax/bytewax
  doc_url: https://bytewax.io/docs
  summary: Python Stateful Stream Processing Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cav71
