{% set name = "bytewax" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bytewax/bytewax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ef36c2da57765a3600a0d2588c821698f9202e0260941c66e1fa1cf67bf92bf4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - maturin
  host:
    - python
    - pip
    - pkg-config
    - make
    - cmake
    - maturin
    - jsonpickle
    - libzlib
    - openssl
    - cyrus-sasl
    - perl  # [ win ]
    - protobuf
    - librdkafka
    - typing-extensions
  run:
    - python
    - protobuf
    - jsonpickle
    - libzlib
    - librdkafka
    - python-confluent-kafka

test:
  source_files:
    - conftest.py
    - pytests
    - examples
  requires:
    - pytest
    - typing-extensions
  commands:
    - pytest -vvs ./pytests

about:
  home: https://bytewax.io
  dev_url: https://github.com/bytewax/bytewax
  doc_url: https://bytewax.io/docs
  summary: Python Stateful Stream Processing Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cav71
