{% set name = "bytewax" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bytewax/bytewax/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8369bb584f172b5b0076d1e65f4d727ca2fcb10e25d7bb768d6a9881673080ac
  patches:
    # this patch disable the vendored ssl/gssapi vendored libraries
    # falling back to use the conda installed ones
    - ssl.patch

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - pkg-config
    - make
    - cmake
    - maturin
    - libzlib
    - openssl
    - cyrus-sasl
    - perl  # [ win ]
    - protobuf
    - librdkafka
  run:
    - python
    - protobuf
    - libzlib
    - librdkafka
    - python-confluent-kafka

test:
  source_files:
    - conftest.py
    - pytests
    - examples
  requires:
    - pytest
  commands:
    - pytest -vvs ./pytests

about:
  home: https://bytewax.io
  dev_url: https://github.com/bytewax/bytewax
  doc_url: https://bytewax.io/docs
  summary: Python Stateful Stream Processing Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cav71
